name: PopulationPacedBorders
version: 4.3.0
main: com.example.PopulationPacedBordersPlugin
depend:
  - Essentials
description: The world border changes depending on the number of players, money and items.
commands:
  ppb:
    description: PopulationPacedBorders help.
    usage: /ppb
author: VaccinoPower
website: https://github.com/VaccinoPower
api-version: '1.20'