name: PopulationPacedBorders
version: 3.0.4
main: com.example.PopulationPacedBordersPlugin
depend:
  - Essentials
description: The world border changes depending on the number of players.
commands:
  ppb:
    description: My description.
    usage: Try /ppb help.
author: VaccinoPower
website: https://github.com/VaccinoPower
api-version: '1.20'