name: PopulationPacedBorders
version: 2.0.3
main: com.example.PopulationPacedBordersPlugin
description: The world border changes depending on the number of players.
author: VaccinoPower
website: https://github.com/VaccinoPower
api-version: '1.20'